version: "3.8"

services:
    app:
        container_name: frontend-web
        image: frontend-web
        build:
            context: ./
            dockerfile: Dockerfile.multi
        volumes:
            - ./dist:/usr/share/nginx/html/
        expose:
            - "80"
        ports:
            - 8888:80
