version: "3.8"

services:
    app:
        container_name: frontend-web
        image: frontend-web
        build:
            context: ./
            dockerfile: Dockerfile.multi
        volumes:
            - ./dist:/usr/share/nginx/html/
        expose:
            - "80"
            - "443"
        ports:
            - 8888:80
            - 4433:443
        networks:
            - myNetwork
networks:
    myNetwork:
        name: frontend_web
