version: "3.8"

services:
    app:
        container_name: backend-web
        image: backend-web
        build:
            context: ./
            dockerfile: Dockerfile.multi
        volumes:
            - ./dist:/usr/share/nginx/html/
        expose:
            - "80"
            - "443"
        ports:
            - 8899:80
            - 4499:443
        networks:
            - myNetwork
networks:
    myNetwork:
        name: backend_web
